name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Install packages
        run: yarn install
      - name: Set Creds
        run: git config user.name "stefan-rink" && git config user.email "rinkyy.sr@googlemail.com"
      - name: Deploy
        run: yarn deploy